title: Welcome to Braintree Support
description: Documentation, Support and Resources for Braintree's Bank Integration app
theme: jekyll-theme-cayman
show_downloads: true
github:
  is_project_page: false